import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LordiconScript from "@/components/LordiconScript";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gaurav Trading co.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden
`}
      >
        <LordiconScript />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
